require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
